### ISSUE TITLE
DB requirement not started when running `make test`

### ISSUE THREAD

**Issue by jcox-dev** [ONSdigital/ras-party#184]
We could do something like [ras-collection-instrument](https://github.com/ONSdigital/ras-collection-instrument/blob/master/tox.ini):

```tox
commands=
    flake8 .
    docker-compose up -d db
    py.test --cov=application --cov-report html --cov-report term-missing []
    docker-compose down
```

**Comment by AdamHawtin** [comment]
The documentation also makes no mention that the tests expect a database to be running on port `6432`.

**Comment by insacuri** [comment]
I don't think it's relevant, will reopen if required
