### ISSUE TITLE
SQLAlchemy table models should reference schema

### ISSUE THREAD

**Issue by tej99** [ONSdigital/ras-party#78]
None of the models reference the table schema. They connect to the right schema because of the use of ras common utils package for db configuration, but the models should have a reference to the schema. 

__table_args__ = {u'schema': 'partysvc'}

**Comment by jcox-dev** [comment]
Is this still relevant with recent changes, @tej99?

**Comment by insacuri** [comment]
Old and probably not relevant anymore.  Will reraise if we realise it's an issue again
